/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/desk.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Low_Poly_Computer_Desk" scale={0.031}>
          <group
            name="CD"
            position={[-76.998, 75.076, 57.333]}
            rotation={[-Math.PI, 1.261, -Math.PI]}
            scale={0.1}>
            <mesh
              name="CD_ComputerDesk_0"
              castShadow
              receiveShadow
              geometry={nodes.CD_ComputerDesk_0.geometry}
              material={materials.ComputerDesk}
            />
          </group>
          <group
            name="CD_case"
            position={[-76.998, 75.356, 57.333]}
            rotation={[-Math.PI, 1.261, -Math.PI]}
            scale={0.064}>
            <mesh
              name="CD_case_ComputerDesk_0"
              castShadow
              receiveShadow
              geometry={nodes.CD_case_ComputerDesk_0.geometry}
              material={materials.ComputerDesk}
            />
          </group>
          <group
            name="Computer_case"
            position={[-55.078, 74.815, 31.19]}
            rotation={[0, 0.036, 0]}
            scale={0.229}>
            <mesh
              name="Computer_case_ComputerDesk_0"
              castShadow
              receiveShadow
              geometry={nodes.Computer_case_ComputerDesk_0.geometry}
              material={materials.ComputerDesk}
            />
          </group>
          <group
            name="Computer_monitor001"
            position={[-3.9, 74.815, 28.04]}
            scale={[0.192, 0.144, 0.096]}>
            <mesh
              name="Computer_monitor001_ComputerDesk_0"
              castShadow
              receiveShadow
              geometry={nodes.Computer_monitor001_ComputerDesk_0.geometry}
              material={materials.ComputerDesk}
            />
          </group>
          <group
            name="Cube000"
            position={[10.874, 0, 115.729]}
            rotation={[0, 0.58, 0]}
            scale={0.394}
          />
          <group name="Drawers" position={[65.098, 0, 55.308]}>
            <mesh
              name="Drawers_ComputerDesk_0"
              castShadow
              receiveShadow
              geometry={nodes.Drawers_ComputerDesk_0.geometry}
              material={materials.ComputerDesk}
            />
          </group>
          <group
            name="Floppy_disk"
            position={[-41.906, 74.815, 65.87]}
            rotation={[Math.PI / 2, 0, 0.247]}>
            <mesh
              name="Floppy_disk_FloppyDisk_0"
              castShadow
              receiveShadow
              geometry={nodes.Floppy_disk_FloppyDisk_0.geometry}
              material={materials.FloppyDisk}
            />
          </group>
          <group name="Keyboard" position={[-3.76, 74.815, 55.898]} scale={0.305}>
            <mesh
              name="Keyboard_ComputerDesk_0"
              castShadow
              receiveShadow
              geometry={nodes.Keyboard_ComputerDesk_0.geometry}
              material={materials.ComputerDesk}
            />
          </group>
          <group name="KeyboardCable" position={[34.329, 76.164, 56.062]}>
            <mesh
              name="KeyboardCable_ComputerDesk_0"
              castShadow
              receiveShadow
              geometry={nodes.KeyboardCable_ComputerDesk_0.geometry}
              material={materials.ComputerDesk}
            />
          </group>
          <group name="Monitor_cable" position={[-3.9, 74.815, 28.04]}>
            <mesh
              name="Monitor_cable_ComputerDesk_0"
              castShadow
              receiveShadow
              geometry={nodes.Monitor_cable_ComputerDesk_0.geometry}
              material={materials.ComputerDesk}
            />
          </group>
          <group name="Mouse" position={[34.329, 76.164, 56.062]} scale={0.271}>
            <mesh
              name="Mouse_ComputerDesk_0"
              castShadow
              receiveShadow
              geometry={nodes.Mouse_ComputerDesk_0.geometry}
              material={materials.ComputerDesk}
            />
          </group>
          <group name="Mouse_cord" position={[34.329, 76.164, 56.062]}>
            <mesh
              name="Mouse_cord_ComputerDesk_0"
              castShadow
              receiveShadow
              geometry={nodes.Mouse_cord_ComputerDesk_0.geometry}
              material={materials.ComputerDesk}
            />
          </group>
          <group
            name="Mousepad"
            position={[42.964, 74.815, 54.261]}
            rotation={[0, -0.115, 0]}
            scale={0.149}>
            <mesh
              name="Mousepad_ComputerDesk_0"
              castShadow
              receiveShadow
              geometry={nodes.Mousepad_ComputerDesk_0.geometry}
              material={materials.ComputerDesk}
            />
          </group>
          <group name="Office_desk" scale={0.271}>
            <mesh
              name="Office_desk_ComputerDesk_0"
              castShadow
              receiveShadow
              geometry={nodes.Office_desk_ComputerDesk_0.geometry}
              material={materials.ComputerDesk}
            />
          </group>
          <group
            name="Paper"
            position={[74.855, 74.63, 39.723]}
            rotation={[0, 0.12, 0]}
            scale={0.1}>
            <mesh
              name="Paper_ComputerDesk_0"
              castShadow
              receiveShadow
              geometry={nodes.Paper_ComputerDesk_0.geometry}
              material={materials.ComputerDesk}
            />
          </group>
          <group
            name="Paper2"
            position={[76.15, 75.001, 39.723]}
            rotation={[0, 0.031, 0]}
            scale={0.1}>
            <mesh
              name="Paper2_ComputerDesk_0"
              castShadow
              receiveShadow
              geometry={nodes.Paper2_ComputerDesk_0.geometry}
              material={materials.ComputerDesk}
            />
          </group>
          <group
            name="Pen"
            position={[76.512, 76.014, 45.557]}
            rotation={[0, 0.244, 0]}
            scale={0.005}>
            <mesh
              name="Pen_ComputerDesk_0"
              castShadow
              receiveShadow
              geometry={nodes.Pen_ComputerDesk_0.geometry}
              material={materials.ComputerDesk}
              position={[0, -0.001, 0.001]}
            />
          </group>
          <group name="Phone_stand" position={[50.705, 74.815, 18.869]} rotation={[0, -0.193, 0]}>
            <mesh
              name="Phone_stand_ComputerDesk_0"
              castShadow
              receiveShadow
              geometry={nodes.Phone_stand_ComputerDesk_0.geometry}
              material={materials.ComputerDesk}
            />
          </group>
          <group
            name="Phonehandle"
            position={[46.949, 79.24, 18.508]}
            rotation={[0.167, -0.19, 0.032]}
            scale={0.263}>
            <mesh
              name="Phonehandle_ComputerDesk_0"
              castShadow
              receiveShadow
              geometry={nodes.Phonehandle_ComputerDesk_0.geometry}
              material={materials.ComputerDesk}
            />
          </group>
          <group
            name="SpeakerL"
            position={[27.417, 74.815, 27.427]}
            rotation={[0, -0.102, 0]}
            scale={0.18}>
            <mesh
              name="SpeakerL_ComputerDesk_0"
              castShadow
              receiveShadow
              geometry={nodes.SpeakerL_ComputerDesk_0.geometry}
              material={materials.ComputerDesk}
            />
          </group>
          <group
            name="SpeakerR"
            position={[-33.15, 74.815, 31.868]}
            rotation={[0, 0.446, 0]}
            scale={0.18}>
            <mesh
              name="SpeakerR_ComputerDesk_0"
              castShadow
              receiveShadow
              geometry={nodes.SpeakerR_ComputerDesk_0.geometry}
              material={materials.ComputerDesk}
            />
          </group>
          <group name="Speakers_cable" position={[27.417, 74.815, 27.427]}>
            <mesh
              name="Speakers_cable_ComputerDesk_0"
              castShadow
              receiveShadow
              geometry={nodes.Speakers_cable_ComputerDesk_0.geometry}
              material={materials.ComputerDesk}
            />
          </group>
        </group>
        <group
          name="ceiling_fan"
          position={[0, 5.13, 1]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.01}>
          <group name="8bb99bb9450a4376981f7b8d79f7960afbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Cylinder">
                  <mesh
                    name="Cylinder_Black_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder_Black_0.geometry}
                    material={materials.Black}
                  />
                </group>
                <group name="decretive_Holder" position={[-0.05, 47.379, 0.001]}>
                  <mesh
                    name="decretive_Holder_White_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.decretive_Holder_White_0.geometry}
                    material={materials.White}
                  />
                </group>
                <group name="Filament">
                  <mesh
                    name="Filament_Black_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Filament_Black_0.geometry}
                    material={materials.Black}
                  />
                </group>
                <group name="Lamp" position={[0, 53.137, 0]}>
                  <mesh
                    name="Lamp_Blue_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Lamp_Blue_0.geometry}
                    material={materials.Blue}
                  />
                  <mesh
                    name="Lamp_White_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Lamp_White_0.geometry}
                    material={materials.White}
                  />
                </group>
                <group name="Light_bulb" position={[0, 18.999, 0]}>
                  <mesh
                    name="Light_bulb_Glass_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Light_bulb_Glass_0.geometry}
                    material={materials.Glass}
                  />
                  <mesh
                    name="Light_bulb_Metal_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Light_bulb_Metal_0.geometry}
                    material={materials.Metal}
                  />
                </group>
                <group
                  name="switch_armature"
                  position={[6.29, -3.188, 0]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}>
                  <group name="Object_17">
                    <group name="Object_19" position={[6.055, 0.36, 0.038]} />
                    <skinnedMesh
                      name="Object_20"
                      geometry={nodes.Object_20.geometry}
                      material={materials.Black}
                      skeleton={nodes.Object_20.skeleton}
                    />
                    <skinnedMesh
                      name="Object_21"
                      geometry={nodes.Object_21.geometry}
                      material={materials.Blue}
                      skeleton={nodes.Object_21.skeleton}
                    />
                    <primitive object={nodes._rootJoint} />
                  </group>
                </group>
                <group name="Switch_holder">
                  <mesh
                    name="Switch_holder_Black_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Switch_holder_Black_0.geometry}
                    material={materials.Black}
                  />
                  <mesh
                    name="Switch_holder_Blue_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Switch_holder_Blue_0.geometry}
                    material={materials.Blue}
                  />
                </group>
                <group name="Torus010" position={[6.055, 0.36, 0.038]} />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/desk.glb')
